### ISSUE TITLE
Connecting to OPC server with username/password

### ISSUE THREAD

**Issue by dezo2** [nauful/LibUA#1]
Hi,
many thanks for this library, it seems to be exactly what I need to develop simple client for data exchange with PLC running OPC server. A simple dll with all the required functionality. When using anonymous server access, everything works as expected (apart some TODO exceptions here and there, which I don't need anyway). However I have one problem regarding session with UserTokenType.UserName - is this implemented?

The user with password is defined on OPC server, there is an endpoint without security (MessageSecurity.None, SecurityPolicy.None) and UserTokenPolicy "Username". Every function in connection sequence return StatusCode Good including ActivateSession:

client.Connect();
client.OpenSecureChannel(MessageSecurityMode.None, SecurityPolicy.None, srv_cert);
var appDesc = new ApplicationDescription("urn:qs:TestClient", "uri:qs:TestClient",
  new LocalizedText("OPC Test Client"), ApplicationType.Client, null, null, null);
client.CreateSession(appDesc, "urn:qs:TestClient", 120);
string username = textBoxUser.Text;
byte[] password = (new System.Text.UTF8Encoding()).GetBytes(textBoxPass.Text);
object usr_identity = new UserIdentityUsernameToken(srv_policy, username, password, Types.SignatureAlgorithmRsa15);
client.ActivateSession(usr_identity, new[] { "en" });

Variables srv_cert (correct array of bytes) and srv_policy ("1" matching the UserTokenPolicy "Username") are loaded before the Connect function from server using your example client code. Weird thing is the ActivateSession returns Good even when the username/password is wrong or missing. I looked into the source code of ActivateSession and found no handler for StatusCode.BadUserAccessDenied. Any attempt to browse nodes using function Browse in this "Good" session ends with exception about array dimensions. The Browse function tries to create an array with impossible length in numRefDesc right after the server response:
refDescs = new ReferenceDescription[numRefDesc];

I then tried to connect to the server with free Prosys OPC UA client application and for username/password access it worked as expected - wrong user was rejected, correct one was allowed. But I don't have sources for the client to look at obviously. 

One more thing - I also tried latest official OPC UA stack from OPCFoundation here on GitHub, compiled the client example and upon connection with the same access as in the Prosys client and my client it ended with 5 exception about security, so it cannot connect to the server with those official libraries too, so I am at lost here as in the Prosys client it somehow worked...

**Comment by nauful** [comment]
Hello,

Yes, UserIdentityUsernameToken is correctly implemented according to the official OPC UA specification.

ActivateSession will return with any bad status code, such as BadUserAccessDenied. If the official OPC UA client cannot connect to the same server, then I think your UA server does not exactly follow the binary serialization specification. In this case, numRefDesc in Browse might also not work because the data structure deserialized does not match the specification. AFAIK, I've tested with 20+ commercial UA servers from different vendors, and Browse/BrowseNext functionality has always worked.

Not all OPC UA providers follow the specification. For more information, you might try using the OpcUa plugin for Wireshark to sniff and disassemble traffic between the Prosys OPC UA client and server, and look at the message structure. If you attach that information here, I could also take a look. I suspect one or more structures in the protocol are different from the official specification.
