### ISSUE TITLE
Monitored item delivers errors in clients log

### ISSUE THREAD

**Issue by stefanofraccaro** [nauful/LibUA#116]
When you monitor an item on UaExpert, many errors appears on Log window. The monitored value is refreshed correctly. I tried with UaExpert 1.5.1 and 1.6.3 : same result. LibUA is the latest version, downloaded today, NET trunk ( .NET Framework 4.8 ). The OS is Windows 10 22H2 
![LibUa_Ack_Error](https://user-images.githubusercontent.com/4329578/222411647-5a67117d-c782-4800-be19-bc7d4301f492.png)
.

**Comment by stefanofraccaro** [comment]
[LibUA-Log.log](https://github.com/nauful/LibUA/files/10870682/LibUA-Log.log)

**Comment by stefanofraccaro** [comment]
Maybe I have found the problem, but I don't remember to have never activated these settings. To reproduce the problem, go to Settings -> Configure UaExpert... and set Trace.StackTraceEnabled=true and Trace.SDKTraceEnabled=true
If you revert these settings to its default value (=false) the communication seems fine.

**Comment by nauful** [comment]
Hello,

This is a known warning which I don't plan to fix because it doesn't impact functionality.

More details: acknowledgements and publish notifications are calculated asynchronously so their counts don't line up immediately. I could make this synchronous, which would fix that warning but performance would decrease significantly when publishing many monitored items to many different clients.
