### ISSUE TITLE
Error with ExpandedNodeId

### ISSUE THREAD

**Issue by mosseedwin** [nauful/LibUA#119]
Generated exception when ExpandedNoId has server index.

**Comment by nauful** [comment]
Can you share a Wireshark capture of this case?

**Comment by mosseedwin** [comment]
> ###
> [Apr 30, 2023](#issuecomment-1529011691)

LibUA used as OPC client.

[opcua.zip](https://github.com/nauful/LibUA/files/11368214/opcua.zip)

**Comment by nauful** [comment]
Sorry, I haven't implemented support for `ExpandedNodeId`. To add that, you might implement `VariantCodingSize`, `VariantEncode` and `VariantDecode` here and the lines under that:

https://github.com/nauful/LibUA/blob/8462ab98c820c87a82e8b0a1e418eb6365c7fb01/NET%20Core/LibUA/Encoding.cs#L967

Otherwise I will add this to my research list and implement this type in the future.
