### ISSUE TITLE
Missing type information for method calls.

### ISSUE THREAD

**Issue by antroa** [nauful/LibUA#20]
The uaexpert client can show input- and output value fields build from type information supported by the method node. Did libua demo server support these informations?

**Comment by nauful** [comment]
You could add this by returning appropriate type information in the read node method, but this isn't included by default due to increased memory requirements to store that information. The spec is lax in terms of definitions.

**Comment by antroa** [comment]
Thank you for your answer (also regarding my other questions). Yes, the spec. is lax. Therefore, the CTT exists to clarify the question "what is conform", more than the spec., but of course not 100%.
Have you plans to test libua with CTT?

**Comment by nauful** [comment]
No, most vendor implementations don't fit the CTT, and changes in the OPC Foundation stack often break the CTT in contradicting ways.

I usually test against several major vendors (OPC Foundation, Yokogawa, Prosys, some smaller ones that our company's clients use). I aim for general wide-spread compatibility rather than rare features which aren't otherwise necessary, works very well for most use cases.
