### ISSUE TITLE
Create Subscription

### ISSUE THREAD

**Issue by paolotraversi** [nauful/LibUA#38]
Hi, i try to create a Subscription with using datachangedfilter monitor variable. I write my code and i don't khow to use where you find "DataChangeFilter .... ??"

      uint subscrId;
      client.CreateSubscription(0, 1000, true, 0, out subscrId);

      // Second will have response BadSubscriptionIdInvalid
      client.SetPublishingMode(true, new[] {subscrId, 10u}, out var respStatuses);

      uint respStatus;
      client.ModifySubscription(subscrId, 0, 100, true, 0, out respStatus);

      uint clientHandleEventMonitor = 0;
      var tagsMonitorId = new uint[2];
      for (var i = 0; i < 2; i++) tagsMonitorId[i] = (uint) (1 + i);

      MonitoredItemCreateResult[] monitorCreateResults;
      client.CreateMonitoredItems(subscrId, TimestampsToReturn.Both,
        new[]
        {
          new MonitoredItemCreateRequest(
            new ReadValueId(new NodeId(2, "PLC_GE_P10.D1.R7001 S"), NodeAttribute.EventNotifier, null, new QualifiedName()),
            MonitoringMode.Reporting,
            new MonitoringParameters(clientHandleEventMonitor, 0, "DataChangeFilter .... ??", 100, true)),

          new MonitoredItemCreateRequest(
            new ReadValueId(new NodeId(2, "PLC_GE_P10.D1.R7003 L"), NodeAttribute.Value, null, new QualifiedName()),
            MonitoringMode.Reporting,
            new MonitoringParameters(tagsMonitorId[0], 0, null, 100, false)),

          new MonitoredItemCreateRequest(
            new ReadValueId(new NodeId(2, "PLC_GE_P10.D1.R7005 L"), NodeAttribute.Value, null, new QualifiedName()),
            MonitoringMode.Reporting,
            new MonitoringParameters(tagsMonitorId[1], 0, null, 100, false)),
        }, out monitorCreateResults);

How can i use DataChangeFilter?

Thanks in advance

**Comment by nauful** [comment]
DataChangeFilter isn't implemented because I don't have a sample server to verify that it actually works. If you want to add it, you could change EventFilter in MonitoredItemCreateRequest to ExtensionObject and implement serialization for DataChangeFilter.

In theory it's useful for only being notified if data value changes exceed a threshold (absolute or relative percentage). In practice, with MonitoringMode.Reporting, values are only published when they change (queue of changes).
