### ISSUE TITLE
Server: Monitor value change

### ISSUE THREAD

**Issue by d1den** [nauful/LibUA#43]
Hi!
I need to monitor a node on a client. But there is no value displayed in the client monitoring window. 
![image](https://user-images.githubusercontent.com/67658531/110625739-de601c80-81b0-11eb-8518-29942dded070.png)

How to set up monitoring so that new values are displayed correctly?
Need this function to display updated values? How to use it (I didn't succeed)?
![image](https://user-images.githubusercontent.com/67658531/110625548-9e993500-81b0-11eb-9724-f1137cb1e403.png)

Thank you in advance

**Comment by nauful** [comment]
If you subscribe to a node in the sample server application from the client, do you see new values getting published?

**Comment by d1den** [comment]
No, it is displayed as in the screenshot above (DataValue is not displayed)

**Comment by nauful** [comment]
What happens if you use UaExpert instead of the client?

Could you also take a Wireshark capture of network traffic?

**Comment by d1den** [comment]
Tried monitoring in UaExpert:  
![image](https://user-images.githubusercontent.com/67658531/110752650-9b588480-8256-11eb-8dc5-6b3b99f0e85b.png)

**Comment by nauful** [comment]
In that version of UaExpert, what does it look like if you subscribe to a publishing node in the sample test server?

Also, could you take a Wireshark capture of network traffic with security set to None?

**Comment by d1den** [comment]
Several tests:  
1. Sample test server monitoring in UaExpert:  
![image](https://user-images.githubusercontent.com/67658531/111151931-2d3af700-85a1-11eb-8870-9402979250d9.png)
It`s working, but some error.
2. In Matricon Opc Ua Explorer:  
![image](https://user-images.githubusercontent.com/67658531/111151895-23b18f00-85a1-11eb-9037-11315a2f40be.png)
When you add a variable to monitoring, an error is generated and the connection is disabled.  
3. In Prosys Opc Ua Client:  
![image](https://user-images.githubusercontent.com/67658531/111152114-6ecba200-85a1-11eb-9178-c2ade1b0c3d2.png)

And I will do Wireshark Capture soon.

**Comment by d1den** [comment]
Wireshark Capture in multiple programs: https://drive.google.com/drive/folders/1t0SpjmXAlYrrWpVx9pHYESY1yooEb1R-?usp=sharing

**Comment by nauful** [comment]
Can you upload the 3 clients?

**Comment by d1den** [comment]
The clients: https://drive.google.com/drive/folders/1p7z_6tT8pFVGvst7kMaDOnXu_RhMpVnB?usp=sharing

**Comment by nauful** [comment]
For uaexpert, looks like PublishRequest includes an array of acknowledged publishes (subscription id, sequence number) and expects the next PublishResponse to include a list of status code updates on those acknowledges if I understand correctly. Those errors show up sporadically due to timing differences between uaexpert acknowledging a publish and the next response containing a useless "good" for that.

Not sure how fixing that would work because publishes are done asynchronously for performance reasons (either on timer, immediately when queued or triggers), but it's safe to disregard that warning I believe.

Matrikon is calling SetMonitoringMode, which isn't currently supported. I'll add support for that.

Looks like Prosys isn't sending any publish requests, will look for a workaround.

**Comment by nauful** [comment]
Matrikon fixed: https://github.com/nauful/LibUA/commit/4b6df3f06ce5f46ef57c1ccda01444491b055c75

**Comment by nauful** [comment]
I've added more UA address space variables that Prosys UA client tries to read when connecting, but it still won't send a PublishRequest.

Previous issue here: https://github.com/nauful/LibUA/issues/25

Closing for now, until I find more information about Prosys client. Other two clients are working now.

**Comment by d1den** [comment]
Thank you for the help!
