### ISSUE TITLE
Writing tag problem

### ISSUE THREAD

**Issue by byrialsen** [nauful/LibUA#71]
Hi

I assume this is more a noob question. I get this null reference exception. Do you have any idea what I do wrong. I believe it is related to the NodeId constructor.

![image](https://user-images.githubusercontent.com/1816703/150757513-63ac1193-cd62-4f83-93a5-8bea34ef270e.png)

**Comment by nauful** [comment]
Hello,

You should define that NodeId as NodeId(3, "\"dbMsi\".\"toSf\".\"WatchDog\").
ns=3;s=... is the serialized form of NodeId. Alternative, you could have used NodeId.Parse with that string. Otherwise the node id will not match as it is right now.

Could you tell me what object is causing that null reference exception? It should be fine.

**Comment by nauful** [comment]
That should have solved your issue. Please leave a comment if you still have this problem.
