### ISSUE TITLE
How connect to server just with username/password

### ISSUE THREAD

**Issue by Gfreeddos** [nauful/LibUA#77]
Hello.
Thanks you for tis project.
How can I use start server just accept connect with username and password.
I found PolicyId but dont know how use it. And method SessionValidateClientUser. Where create username and password? 
Help please.

**Comment by nauful** [comment]
To only accept username+password authentication, remove all `UserTokenPolicy` other than `UserTokenPolicy.UserName` and remove `epNoSecurity ` entirely here:
https://github.com/nauful/LibUA/blob/7c9e1a22ba38743af4dbdd3bdb1420788e2238e6/NET%20Core/TestServer/Program.cs#L132

You can validate username and password here:
https://github.com/nauful/LibUA/blob/7c9e1a22ba38743af4dbdd3bdb1420788e2238e6/NET%20Core/TestServer/Program.cs#L122
For example, call a method with this signature: `return validateUser(username, password);` instead of `return true`

**Comment by Gfreeddos** [comment]
I am comment all UserTokenType.Anonymous in 
`public override IList<EndpointDescription> GetEndpointDescriptions(string endpointUrlHint)`
And server send error (requires username and password). 

But, how can I use 
`public override bool SessionValidateClientUser(object session, object userIdentityToken)`
to save username and password on server and validate in my programm?

Thx.

**Comment by nauful** [comment]
Can you upload a Wireshark traffic capture here with no security and UserTokenType.UserName? This will show me what error happened which led to the server closing the channel.

**Comment by Gfreeddos** [comment]
I am comment:
`HandleHistoryEventReadRequest` , `HandleHistoryReadRequest`, `PlayRow` in to your simple example Server, and my server nice work with access just username and password (without channel close).
Thnx
