### ISSUE TITLE
Default address space

### ISSUE THREAD

**Issue by dstickel** [nauful/LibUA#78]
Can the default address space be reduced for a minimalist build? While still being able to perform read / write, browsing, historical, and alarms?

**Comment by nauful** [comment]
Yes. You could remove everything but the basic server node. If you provide a single root node for your own nodes, you don't need any of the default address space.

I have done this in practice. Some UA specific clients complain while browsing (undefined server status, undefined relation types, etc), but all functionality still works.

**Comment by dstickel** [comment]
I have tried this and you are correct on the browsing. I have issues with it throwing exceptions when trying to browse from other clients. What would need to be used in the default address space to allow other clients to browse still? I know there is a lot in this default address space but would like to cut it down to the minimum. I could comment out one line at a time but that would take forever so looking for some pointers on what to keep in there. Appeciate any input you could give me.

**Comment by nauful** [comment]
I would guess perhaps node type and variable type information. Trimming down to id<100 should give you all of the primitive types, and trimming to id<1000 will give you "extended types", for lack of a better term.

If that doesn't work, you can upload a wireshark capture here (with no encryption for ua traffic) and I can take a look.

**Comment by dstickel** [comment]
[WiresharkCaptures.zip](https://github.com/nauful/LibUA/files/8534077/WiresharkCaptures.zip)

**Comment by dstickel** [comment]
I took a capture of each. One with the space < 100 and one with the space < 1000. Thank you very much for your assistance with this. Very much appreciated.

**Comment by nauful** [comment]
Looking at the <1000 one:
![image](https://user-images.githubusercontent.com/50109829/164855567-149d5b5a-e581-41a3-8776-b92b41b90348.png)
Looks like an internal error when browsing `ns=0;i=29` with relation type `ns=0;i=45`
Then in `Application.cs`:
https://raw.githubusercontent.com/nauful/LibUA/master/NET%20Core/LibUA/Application.cs
That corresponds to `Enumeration, i=29` with a relationship of `HasSubtype, i=45`.

I would guess that you still have links to the non-existant children (linked by relation type `HasSubtype`) which have ids with a numeric component well above 1000. Browse probably fails because the server tries to resolve the destination nodes before returning.

You might try loading the whole address space, then filtering the address space table by i<1000, then of all nodes in the address space table, filtering references by reference type i<1000 and target node i<1000. If that works, you could just serialize that as your minimal node set.

A more complex approach, and I've done this in the past, is to load the whole address space, then allow a client to run through its normal operations but mark any node visited by the method `HandleReadRequestInternal`. At the end, any node or reference target not marked is filtered out and the remaining nodes can be serialized. This can be done similar to how a mark-and-sweep garbage collector with reference counting works.

**Comment by dstickel** [comment]
Ah...that was the issue. I removed all the address items above the number but not the reference nodes. I reduced it again down to 100 and it works now. With one client I had to add 2259 back. It kept disconnecting without it. Thanks you very much for the help.

**Comment by nauful** [comment]
Glad to hear that it worked. Just FYI, 2259 is for `ServerState`. Some clients subscribe to that to figure out if/when a server starts or shuts down, and potentially for timing information to synchronize clocks between different real-time systems (especially common for embedded systems without reliable clocks). Depending on your clients, you might have to implement those.
